---

version: '3.2'

services:
  cron:
    volumes:
      - type: bind
        source: /data/project/matomo
        target: /srv/matomo/backup
    environment:
      - MATOMO_FQDN=analytics-wikipedialibrary.wmflabs.org
