---

version: '3.2'
# Production environment should use external secrets
secrets:
  MYSQL_ROOT_PASSWORD:
    external: true
  MATOMO_DATABASE_USERNAME:
    external: true
  MATOMO_DATABASE_PASSWORD:
    external: true

services:
  cron:
    volumes:
      - type: bind
        source: /data/project/matomo
        target: /srv/matomo/backup
      - type: bind
        source: ./cron/conf
        target: /opt/cron/conf
        read_only: true

    environment:
      - MATOMO_FQDN=analytics-wikipedialibrary.wmflabs.org
