---
# modified from:
# https://github.com/matomo-org/docker/blob/dc52ce5b12b7cee74e9afa26ee73af07c26e6012/.examples/nginx/docker-compose.yml
version: '3.2'

volumes:
  db:
  matomo:

services:
  db:
    image: quay.io/wikipedialibrary/mariadb:10
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
  app:
    image: quay.io/wikipedialibrary/matomo:fpm-alpine
    restart: always
    links:
      - db
    volumes:
#      - ./config:/var/www/html/config:rw
#      - ./logs:/var/www/html/logs
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
  web:
    image: quay.io/wikipedialibrary/nginx:latest
    restart: always
    volumes:
      - matomo:/var/www/html:ro
      # see https://github.com/matomo-org/matomo-nginx
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
