---
# modified from:
# https://github.com/matomo-org/docker/blob/dc52ce5b12b7cee74e9afa26ee73af07c26e6012/.examples/nginx/docker-compose.yml
version: '3.2'

volumes:
  db:
  matomo:

services:
  db:
    image: quay.io/wikipedialibrary/mariadb:10
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    environment:
      - MYSQL_DATABASE=matomo
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/MYSQL_ROOT_PASSWORD
      - MYSQL_USER_FILE=/run/secrets/MATOMO_DATABASE_USERNAME
      - MYSQL_PASSWORD_FILE=/run/secrets/MATOMO_DATABASE_PASSWORD
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MATOMO_DATABASE_USERNAME
      - MATOMO_DATABASE_PASSWORD
  app:
    image: quay.io/wikipedialibrary/matomo:fpm-alpine
    restart: always
    volumes:
      - type: volume
        source: matomo
        target: /var/www/html
      - type: bind
        source: ./logs
        target: /var/www/html/logs
      - type: bind
        source: ./entrypoint.sh
        target: /entrypoint.sh
    environment:
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_DBNAME=matomo
    secrets:
      - MATOMO_DATABASE_USERNAME
      - MATOMO_DATABASE_PASSWORD
  web:
    image: quay.io/wikipedialibrary/nginx:latest
    restart: always
    volumes:
      - type: volume
        source: matomo
        target: /var/www/html
        read_only: true
      # see https://github.com/matomo-org/matomo-nginx
      - type: bind
        source: ./conf/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:80
